"use client";
import Header from "@/components/Header";
import InputBar from "@/components/InputBar";
import MessageArea from "@/components/MessageArea";
import React, { useState, useEffect, useRef } from "react";

interface Message {
  id: number;
  content: string;
  isUser: boolean;
  type: "user" | "assistant";
  isStreaming?: boolean;
}

const Home = () => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 1,
      content: "Hello! I'm your ChatBot assistant. How can I help you today?",
      isUser: false,
      type: "assistant",
    },
  ]);
  const [currentMessage, setCurrentMessage] = useState("");
  const [sessionId, setSessionId] = useState<string>("");
  const [isLoading, setIsLoading] = useState(false);
  const streamingTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Generate session ID on component mount
  useEffect(() => {
    const newSessionId = `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    setSessionId(newSessionId);
  }, []);

  // Cleanup streaming timeout on unmount
  useEffect(() => {
    return () => {
      if (streamingTimeoutRef.current) {
        clearTimeout(streamingTimeoutRef.current);
      }
    };
  }, []);

  const simulateStreaming = (fullText: string, messageId: number) => {
    // Split text into chunks (by words for smoother streaming)
    const words = fullText.split(' ');
    let currentIndex = 0;
    
    // Add initial empty message and IMMEDIATELY stop the loading indicator
    setMessages((prev) => [
      ...prev,
      { 
        id: messageId, 
        content: "", 
        isUser: false, 
        type: "assistant",
        isStreaming: true
      },
    ]);
    
    // Stop loading immediately when streaming starts
    setIsLoading(false);

    const streamNextChunk = () => {
      if (currentIndex < words.length) {
        const chunkSize = Math.floor(Math.random() * 3) + 1; // 1-3 words per chunk
        const chunk = words.slice(currentIndex, currentIndex + chunkSize).join(' ');
        currentIndex += chunkSize;

        setMessages((prev) => {
          const updated = [...prev];
          const lastMessage = updated[updated.length - 1];
          if (lastMessage.id === messageId) {
            lastMessage.content = words.slice(0, currentIndex).join(' ');
            if (currentIndex >= words.length) {
              lastMessage.isStreaming = false;
            }
          }
          return updated;
        });

        // Random delay between 30-80ms for natural feel
        const delay = Math.random() * 50 + 30;
        streamingTimeoutRef.current = setTimeout(streamNextChunk, delay);
      }
    };

    streamNextChunk();
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentMessage.trim() || isLoading) return;

    // Clear any existing streaming timeout
    if (streamingTimeoutRef.current) {
      clearTimeout(streamingTimeoutRef.current);
    }

    // Add user message
    const userMessageId = messages.length + 1;
    setMessages((prev) => [
      ...prev,
      { id: userMessageId, content: currentMessage, isUser: true, type: "user" },
    ]);

    const userInput = currentMessage;
    setCurrentMessage("");
    setIsLoading(true);

    try {
      // Send request to FastAPI
      const response = await fetch("http://localhost:8000/chat", {
        method: "POST",
        headers: { 
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ 
          message: userInput,
          session_id: sessionId 
        }),
      });

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();
      const aiContent = data.response || "Sorry, I couldn't process your request.";
      
      // Update session ID if it was generated by the server
      if (data.session_id && data.session_id !== sessionId) {
        setSessionId(data.session_id);
      }

      // Start streaming simulation
      simulateStreaming(aiContent, userMessageId + 1);
      
    } catch (error) {
      console.error("Chat error:", error);
      setMessages((prev) => [
        ...prev,
        { 
          id: messages.length + 2, 
          content: "Sorry, I'm having trouble connecting to the server. Please try again.", 
          isUser: false, 
          type: "assistant" 
        },
      ]);
      setIsLoading(false);
    }
  };

  const clearChat = () => {
    // Clear any existing streaming timeout
    if (streamingTimeoutRef.current) {
      clearTimeout(streamingTimeoutRef.current);
    }
    
    setMessages([
      {
        id: 1,
        content: "Hello! I'm your ChatBot assistant. How can I help you today?",
        isUser: false,
        type: "assistant",
      },
    ]);
    // Generate new session ID
    const newSessionId = `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    setSessionId(newSessionId);
    setIsLoading(false);
  };

  return (
    <div className="flex justify-center bg-gray-100 min-h-screen py-8 px-4">
      <div className="w-full max-w-6xl bg-white flex flex-col rounded-xl shadow-lg border border-gray-100 overflow-hidden h-[90vh]">
        <Header />
        <MessageArea messages={messages} isLoading={isLoading} />
        <InputBar
          currentMessage={currentMessage}
          setCurrentMessage={setCurrentMessage}
          onSubmit={handleSubmit}
          isLoading={isLoading}
        />
      </div>
    </div>
  );
};

export default Home;